name: Build MacOS
on:
  workflow_dispatch: {}
jobs:
  Build_MacOS:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3
      
      # Step 2: Setup Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # Step 3: Confirm Flutter version
      - name: Check Flutter Version
        run: flutter --version
      
      # Step 4: Get dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Step 5: Build generated code
      - name: Run build_runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
      # Step 6: Build Mac app
      - name: Build Mac app (release)
        run: flutter build macos --profile

      # Step 7: Create Payload directory and move Runner.app
      - name: Prepare Payload directory
        run: |
          mkdir -p build/MacOS/Payload build/macos/Build/Products/Release/pica_comic.app
          mv build/MacOS/Runner.app build/MacOS/Payload

      - uses: actions/upload-artifact@v4
        with:
          name: macos-build.zip
          path: build/macos/Build/Products/Release/pica_comic.app
